import { useMemo, memo, useCallback } from 'react';
import { useApp } from '../../context/AppContext';
import { Download, Mail, Eye, Plus, FileSpreadsheet, FileText } from 'lucide-react';
import { PanelHeader } from '../shared/PanelHeader';

export const FormatBadge = memo(function FormatBadge({ format }) {
  let badgeStyle = { bg: 'rgba(220, 38, 38, 0.12)', color: '#b91c1c', border: 'rgba(220, 38, 38, 0.3)' };

  if (format === 'Excel') {
    badgeStyle = { bg: 'rgba(22, 163, 74, 0.12)', color: '#15803d', border: 'rgba(22, 163, 74, 0.3)' };
  } else if (format === 'CSV') {
    badgeStyle = { bg: 'rgba(37, 99, 235, 0.12)', color: '#1d4ed8', border: 'rgba(37, 99, 235, 0.3)' };
  }

  return (
    <span
      className="badge mono-data"
      style={{
        background: badgeStyle.bg,
        color: badgeStyle.color,
        border: `1px solid ${badgeStyle.border}`,
        fontSize: '0.65rem'
      }}
    >
      {format}
    </span>
  );
});

export const RecentGeneratedReportsTable = memo(function RecentGeneratedReportsTable({ onOpenCustomModal, onPreviewReport }) {
  const { generatedReports, selectedReport, setSelectedReport, navigateTo, showToast } = useApp();

  const handleReportSelect = useCallback((item) => {
    setSelectedReport(item);
    onPreviewReport(item);
  }, [setSelectedReport, onPreviewReport]);

  const handleReportKeyDown = useCallback((e, item) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      handleReportSelect(item);
    }
  }, [handleReportSelect]);

  const handleDownload = useCallback((e, item) => {
    e.stopPropagation();
    showToast(`Downloading "${item.name}" (${item.format})...`, 'success');
  }, [showToast]);

  const handleEmail = useCallback((e, item) => {
    e.stopPropagation();
    showToast(`Emailed report "${item.name}" to recipients`, 'info');
  }, [showToast]);

  return (
    <div className="panel-card" style={{ padding: '1.25rem' }}>
      <PanelHeader
        title="Recent Generated Reports Log"
        accentColor="#2563eb"
        actionLabel="SCHEDULED REPORTS →"
        onAction={() => navigateTo('reports', 'Scheduled Reports')}
      >
        <button
          className="btn btn-primary btn-sm"
          onClick={onOpenCustomModal}
          aria-label="Build Custom Report"
        >
          <Plus size={14} aria-hidden="true" /> BUILD CUSTOM REPORT
        </button>
      </PanelHeader>

      <div style={{ overflowX: 'auto', border: '1px solid var(--border-color)', borderRadius: '4px' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '0.8rem' }} aria-label="Recent generated reports log table">
          <thead>
            <tr style={{ background: 'var(--bg-input)', borderBottom: '1px solid var(--border-color)', fontSize: '0.7rem', color: 'var(--text-muted)' }}>
              <th style={{ padding: '0.65rem 0.75rem' }}>REPORT ID</th>
              <th style={{ padding: '0.65rem 0.75rem' }}>REPORT NAME</th>
              <th style={{ padding: '0.65rem 0.75rem' }}>MODULE</th>
              <th style={{ padding: '0.65rem 0.75rem' }}>GENERATED BY</th>
              <th style={{ padding: '0.65rem 0.75rem' }}>DATE & TIME</th>
              <th style={{ padding: '0.65rem 0.75rem' }}>FORMAT</th>
              <th style={{ padding: '0.65rem 0.75rem', textAlign: 'right' }}>ACTIONS</th>
            </tr>
          </thead>
          <tbody>
            {generatedReports.slice(0, 5).map((item) => {
              const isSelected = selectedReport?.id === item.id;

              return (
                <tr
                  key={item.id}
                  tabIndex={0}
                  role="button"
                  onClick={() => handleReportSelect(item)}
                  onKeyDown={(e) => handleReportKeyDown(e, item)}
                  aria-selected={isSelected}
                  style={{
                    borderBottom: '1px solid var(--border-color)',
                    background: isSelected ? 'rgba(37, 99, 235, 0.08)' : 'transparent',
                    cursor: 'pointer',
                    transition: 'background 0.2s ease'
                  }}
                >
                  <td className="mono-data" style={{ padding: '0.75rem', fontWeight: '700', color: 'var(--precision-blue)' }}>
                    {item.id}
                  </td>
                  <td style={{ padding: '0.75rem', fontWeight: '700' }}>
                    {item.name}
                  </td>
                  <td style={{ padding: '0.75rem', fontSize: '0.725rem' }}>
                    <span className="badge badge-info mono-data" style={{ fontSize: '0.625rem' }}>
                      {item.module}
                    </span>
                  </td>
                  <td style={{ padding: '0.75rem', fontSize: '0.725rem' }}>
                    {item.generatedBy}
                  </td>
                  <td className="mono-data" style={{ padding: '0.75rem', fontSize: '0.725rem' }}>
                    {item.dateTime}
                  </td>
                  <td style={{ padding: '0.75rem' }}>
                    <FormatBadge format={item.format} />
                  </td>
                  <td style={{ padding: '0.75rem', textAlign: 'right' }}>
                    <div style={{ display: 'flex', gap: '4px', justifyContent: 'flex-end' }}>
                      <button
                        className="btn btn-secondary btn-sm"
                        style={{ padding: '3px 7px' }}
                        onClick={(e) => handleDownload(e, item)}
                        title="Download File"
                        aria-label={`Download ${item.name}`}
                      >
                        <Download size={12} aria-hidden="true" />
                      </button>
                      <button
                        className="btn btn-secondary btn-sm"
                        style={{ padding: '3px 7px' }}
                        onClick={(e) => handleEmail(e, item)}
                        title="Email Report"
                        aria-label={`Email ${item.name}`}
                      >
                        <Mail size={12} aria-hidden="true" />
                      </button>
                      <button
                        className="btn btn-secondary btn-sm"
                        style={{ padding: '3px 7px' }}
                        onClick={(e) => {
                          e.stopPropagation();
                          handleReportSelect(item);
                        }}
                        title="Preview Report"
                        aria-label={`Preview ${item.name}`}
                      >
                        <Eye size={12} aria-hidden="true" />
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
});
