import { memo, useCallback } from 'react';
import { useApp } from '../../context/AppContext';
import { FileText, Download, Mail, Printer, Share2, Calendar } from 'lucide-react';
import { Modal } from '../shared/Modal';
import { FormatBadge } from './RecentGeneratedReportsTable';

export const ReportPreviewModal = memo(function ReportPreviewModal({ isOpen, onClose, report }) {
  const { showToast } = useApp();

  if (!report) return null;

  const handleActionToast = (actionName) => {
    showToast(`Executed ${actionName} for "${report.name || report.title}"`, 'info');
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={`Report Preview — ${report.name || report.title}`}
      icon={<FileText size={18} color="var(--precision-blue)" />}
      width="640px"
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem', fontSize: '0.8rem' }}>
        {/* Top Control Bar */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'var(--bg-input)', padding: '0.65rem 0.85rem', borderRadius: '4px', border: '1px solid var(--border-color)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <FormatBadge format={report.format || 'PDF'} />
            <span style={{ fontWeight: '700' }}>{report.module || 'Analytics'}</span>
          </div>

          <div style={{ display: 'flex', gap: '4px' }}>
            <button
              className="btn btn-secondary btn-sm"
              style={{ padding: '3px 8px', fontSize: '0.675rem' }}
              onClick={() => handleActionToast('Download Excel')}
            >
              <Download size={11} aria-hidden="true" /> Excel
            </button>
            <button
              className="btn btn-secondary btn-sm"
              style={{ padding: '3px 8px', fontSize: '0.675rem' }}
              onClick={() => handleActionToast('Download PDF')}
            >
              <Download size={11} aria-hidden="true" /> PDF
            </button>
            <button
              className="btn btn-secondary btn-sm"
              style={{ padding: '3px 8px', fontSize: '0.675rem' }}
              onClick={() => handleActionToast('Print')}
            >
              <Printer size={11} aria-hidden="true" /> Print
            </button>
            <button
              className="btn btn-secondary btn-sm"
              style={{ padding: '3px 8px', fontSize: '0.675rem' }}
              onClick={() => handleActionToast('Email')}
            >
              <Mail size={11} aria-hidden="true" /> Email
            </button>
            <button
              className="btn btn-secondary btn-sm"
              style={{ padding: '3px 8px', fontSize: '0.675rem' }}
              onClick={() => handleActionToast('Share')}
            >
              <Share2 size={11} aria-hidden="true" /> Share
            </button>
          </div>
        </div>

        {/* Report Overview Data Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.75rem', background: 'var(--bg-card)', padding: '0.85rem', borderRadius: '4px', border: '1px solid var(--border-color)' }}>
          <div>
            <span style={{ color: 'var(--text-muted)', fontSize: '0.7rem', display: 'block' }}>REPORT TITLE</span>
            <span style={{ fontWeight: 800 }}>{report.name || report.title}</span>
          </div>
          <div>
            <span style={{ color: 'var(--text-muted)', fontSize: '0.7rem', display: 'block' }}>MODULE SOURCE</span>
            <span className="mono-data" style={{ fontWeight: 700 }}>{report.module || 'Finance & Sales'}</span>
          </div>
          <div>
            <span style={{ color: 'var(--text-muted)', fontSize: '0.7rem', display: 'block' }}>GENERATED ON</span>
            <span className="mono-data">{report.dateTime || '01 Aug 2026, 10:15 AM'}</span>
          </div>
          <div>
            <span style={{ color: 'var(--text-muted)', fontSize: '0.7rem', display: 'block' }}>GENERATED BY</span>
            <span>{report.generatedBy || 'John Doe (Admin)'}</span>
          </div>
        </div>

        {/* Mock Report Document Preview Area */}
        <div
          style={{
            padding: '1rem',
            background: '#ffffff',
            color: '#0f172a',
            borderRadius: '4px',
            border: '1px solid var(--border-color)',
            fontFamily: 'var(--font-mono)',
            fontSize: '0.725rem',
            lineHeight: 1.5,
            boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.05)'
          }}
        >
          <div style={{ borderBottom: '2px solid #2563eb', paddingBottom: '0.5rem', marginBottom: '0.75rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontWeight: 900, fontSize: '0.85rem', color: '#1e293b' }}>APEX STRUCTURAL ERP — ANALYTICS REPORT</span>
            <span style={{ fontSize: '0.65rem', color: '#64748b' }}>CONFIDENTIAL</span>
          </div>
          <p style={{ margin: 0, fontWeight: 700 }}>{report.description || 'Aggregated multi-period summary analytics report.'}</p>
          <p style={{ margin: '6px 0 0 0', color: '#475569', fontSize: '0.675rem' }}>
            STATUS: REAL-TIME AUDITED DATASET | TOTAL ROWS: 148 RECORDS | HASH: 0x8F92A
          </p>
        </div>
      </div>

      <div className="modal-actions" style={{ marginTop: '1.25rem' }}>
        <button className="btn btn-secondary btn-sm" onClick={onClose}>
          CLOSE PREVIEW
        </button>
      </div>
    </Modal>
  );
});
